In [1]:
#Importing Libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from numpy.linalg import inv

In [2]:
#Data Set

data_set = np.array([[6, 2, 7], [8, 1, 9], [10, 0, 13], [14, 2, 17.5], [18, 0, 18]])
df = pd.DataFrame(data = data_set, index = [str(int(x)) for x in range(5)], columns = ["Daimeter (In Inches)","Number of toppings", "Price(In Dollars)"])
df

Daimeter (In Inches)  Number of toppings  Price(In Dollars)
0                   6.0                 2.0                7.0
1                   8.0                 1.0                9.0
2                  10.0                 0.0               13.0
3                  14.0                 2.0               17.5
4                  18.0                 0.0               18.0

In [21]:
#Model

#y = α + β 1 x 1 + β 2 x 2 + ⋅⋅⋅ + β n x n
#Y = X β
#β = (inv( X T X )  X T Y)

data_x = np.array(df.iloc[:,0:2].values)
data_y = np.array(df.iloc[:,2].values.reshape(-1,1))

data_x, data_y

(array([[ 6.,  2.],
        [ 8.,  1.],
        [10.,  0.],
        [14.,  2.],
        [18.,  0.]]),
 array([[ 7. ],
        [ 9. ],
        [13. ],
        [17.5],
        [18. ]]))

In [14]:
Beta = np.dot(np.linalg.inv(np.dot(data_x.T,data_x)),np.dot(data_x.T,data_y))
Beta

array([[1.08548851],
       [0.65517241]])

In [19]:
data_x_test = [[8, 2], [9, 0], [11, 2], [16, 2], [12, 0]]
data_y_test = [[11], [8.5], [15], [18], [11]]
Y = np.dot(data_x_test,Beta)
Y

array([[ 9.99425287],
       [ 9.76939655],
       [13.25071839],
       [18.67816092],
       [13.02586207]])

In [20]:
#Model

model = LinearRegression()
model.fit(data_x, data_y)
pred = model.predict(data_x_test)
pred

array([[10.0625    ],
       [10.28125   ],
       [13.09375   ],
       [18.14583333],
       [13.3125    ]])